#!/bin/bash

set -e

packfile=$(npm pack 2>/dev/null | tail -n 1)

echo $packfile

tmp_dir=$(mktemp -d -t agent-test-install)

mv $packfile $tmp_dir/

pushd $tmp_dir || exit

npm init --yes
npm install "./$packfile"

popd || exit

echo "Package install test succeeded!"


